# 1. 프로젝트 명
spring.application.name=sb.member.ex01
# 2. 포트설정 localhost:8080 일때는 생략 가능
server.address=0.0.0.0
server.port=${PORT:8080}
# 3. View Resolver 설정(jsp 관련)
# jsp 대신 타임리프를 사용할 경우 생략 가능 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 4. MySQL DB 설정 (기존 DBConnectionMgr의 정보를 여기로 옮깁니다)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
#spring.datasource.username=minho
#spring.datasource.password=zjajj899

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# 5. DevTools 설정
spring.devtools.livereload.enabled=true